server:
  port: 8081
spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  dataSource:
    url: jdbc:mysql://47.104.63.26:3306/cpx?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: ****
    password: ****
    driver-class-name: com.mysql.jdbc.Driver
